### ISSUE TITLE
Vga output problem

### ISSUE THREAD

**Issue by luozhili1999** [mighildotcom/ThinkPad-T530-Hackintosh#1]
Hello, thank you very much for your project. I successfully installed it on the T530. But I encountered a problem that I couldn't export it to the monitor from the vga. I haven't solved it for a few hours. I hope you can provide some help. 

My hardware is the same as you, but I don't have a discrete graphics card. Only HD4000 nuclear display

---Translated by Google

**Comment by mighildotcom** [comment]
I’ve already mentioned it before. VGA port won’t work. Sorry :(

**Comment by verfasor** [comment]
About that, VGA port won’t work. I’m sorry.

**Comment by luozhili1999** [comment]
I am trying to fix it with Clover. I don't know if it works.

**Comment by mighildotcom** [comment]
Let me know if it works, xiexie.

**Comment by verfasor** [comment]
Cool. How about miniDP? did you figure out a way to make it work?

**Comment by luozhili1999** [comment]
I don't have a video cable for miniDP.Is there a successful case? I plan to buy one.

**Comment by luozhili1999** [comment]
Minidp useful    ！
