### ISSUE TITLE
AudioID

### ISSUE THREAD

**Issue by ProfDrLuigi** [mighildotcom/ThinkPad-T530-Hackintosh#2]
Better set to ID29. With ID28 you only have Speaker but no Mic. More futureproof is to set the ID through a boot-arg (alcid=29) and not the Checkbox.
+
CodecCommander is not necessary.

**Comment by verfasor** [comment]
For me, both the speaker and microphone are working with the current setting OOB. I'll look into to anyway. Thank you. Currently using an X230 as the daily driver.

**Comment by ProfDrLuigi** [comment]
If you want any Wlan Card working... at hackintosh-forum.de I started a Thread. There are the Modfiles (Wlan Whitelist, Advanced Menu and Powermanagement) for Bios Version 2.77. And the best thing is ... it's free. In contrast to a relevant forum that specializes in bios mods but wants money for it. (-:  

https://www.hackintosh-forum.de/forum/thread/45205-bios-mod-wwan-whitelist-mit-wenigen-schritten-selbstgemacht/?pageNo=1

And here how to generelly flash the Bios via USB Programmer:
https://www.hackintosh-forum.de/forum/thread/37088-mod-bios-via-programmer-flashen/?pageNo=1

PS:
I´m working on an OpenCore Version. It boots. But no: Sound, Brightness slider, Battery, Sleep, Trackpad (only "Mouse-Mode"). A little bit to do. :)
