### ISSUE TITLE
Just saying hi....

### ISSUE THREAD

**Issue by stavoxnetworks** [mighildotcom/ThinkPad-T530-Hackintosh#4]
I was one of the folks that worked on the Hackintosh with the T530 back when Mountain Lion was out. Its really awesome to see that machine is still around! You have taken it so much further than I ever could have. If there is anything at all I can do to help you out, I would be more than happy to! Great work man.....

**Comment by verfasor** [comment]
So nice to hear that. Unfortunately the machine is not with me now. I relocated temporarily and I'm stuck in another place due to travel ban. I'll test Big Sur on T530 later this year! ;) Will keep you in the loop. Cheers and stay safe!
